# Site settings
title: Museum of Things for People
email: foresight@digipolis.gent
url: https://lab9k.gent/
description: 'Onderzoek naar de waarde van Internet of Things in musea.'
baseurl: /
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# here you can add/remove navigation items. This works with local, and outbound links
navitems:
  - name: over
    url: '#about'
    class: page-scroll
  - name: Doel
    url: '#goal'
    class: page-scroll
  - name: Context
    url: '#context'
    class: page-scroll
  - name: Partners
    url: '#partners'
    class: page-scroll
  - name: blog
    url: 'https://medium.com/@MOTFP'
  - name: contact
    url: '#contact'
    class: page-scroll
  - name: events
    url: '/events'

# use the speaker.columns attribute to specify the width of a column. (out of 12 -> columns===4 means 3 columns per row)
speakers:
  - name: Tom Palmaerts
    page: https://trendwolves.com/
    function: Trendwatcher & Manager trendwolves
    image: /img/sprekers/tompalmaerts.jpg
    columns: 3
    subject: Culture in 2030
  - name: Fredo De Smet
    page: https://www.fredodesmet.com/
    function: Artistiek Consulent Design Museum Gent & Curator Hello Robot
    image: /img/sprekers/fredodesmet.jpg
    columns: 3
    subject: The battle for the third space
  - name: Jasper Visser
    page: https://visschstam.com/
    function: Strategisch adviseur & Senior partner VISSCH+STAMM
    image: /img/sprekers/jaspervisser.jpg
    columns: 3
    subject: Een smart museum voor slimme mensen
  - name: Sara Logghe
    page: https://www.cultuurconnect.be/
    function: Project Manager R&D
    image: /img/sprekers/saralogghe.jpg
    columns: 3
    subject: Panellid: Rol van tech in de cultuursector

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/foresightgent
  - title: facebook
    url: https://www.facebook.com/foresightgent/
  - title: instagram
    url: https://www.instagram.com/foresightgent/?hl=nl
  - title: github
    url: https://github.com/Lab9K

# Build settings
markdown: kramdown
permalink: pretty
