# Site settings
title: Museum of Things for People
email: foresight@digipolis.gent
url: https://lab9k.gent/
description: 'Onderzoek naar de waarde van Internet of Things in musea.'
baseurl: /
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# here you can add/remove navigation items. This works with local, and outbound links
navitems:
  - name: over
    url: '#about'
    class: page-scroll
  - name: Context
    url: '#context'
    class: page-scroll
  - name: Partners
    url: '#partners'
    class: page-scroll
  - name: blog
    url: 'https://medium.com/@MOTFP'
  - name: documentatie
    url: 'https://motfp.gitbook.io/documentatie/'
  - name: contact
    url: '#contact'
    class: page-scroll
  - name: events
    url: '/events'

# use the speaker.columns attribute to specify the width of a column. (out of 12 -> columns===4 means 3 columns per row)
speakers:
  - name: Tom Palmaerts
    page: https://trendwolves.com/
    function: Trendwatcher & Manager trendwolves
    image: /img/sprekers/tompalmaerts.jpg
    columns: 3
    subject: Culture in 2030
    panel: false
  - name: Fredo De Smet
    page: https://www.fredodesmet.com/
    function: Artistiek Consulent Design Museum Gent & Curator Hello Robot
    image: /img/sprekers/fredodesmet.jpg
    columns: 3
    subject: The battle for the third space
    panel: false
  - name: Jasper Visser
    page: https://visschstam.com/
    function: Strategisch adviseur & Senior partner VISSCH+STAMM
    image: /img/sprekers/jaspervisser.jpg
    columns: 3
    subject: Een smart museum voor slimme mensen
    panel: false
  - name: Luc Delrue
    page: https://cjsm.be/cultuur/
    function: Secretaris-generaal van het Departement Cultuur, Jeugd en Media in Vlaanderen
    image: /img/sprekers/lucdelrue.jpg
    columns: 4
    subject: 'Rol van tech in de cultuursector'
    panel: true
  - name: Sara Logghe
    page: https://www.cultuurconnect.be/
    function: Project Manager R&D
    image: /img/sprekers/saralogghe.jpg
    columns: 3
    subject: 'Rol van tech in de cultuursector'
    panel: true
  - name: Dries Depoorter
    page: https://driesdepoorter.be/
    function: Creative Technologist / Artist
    image: /img/sprekers/driesdepoorter.jpg
    columns: 3
    subject: DriesDepoorter.key
    panel: false
  - name: Annelies Desmet
    page: https://deartech.org/
    function: Co-founder Dear Tech
    image: /img/sprekers/anneliesdesmet.jpg
    columns: 3
    subject: 'Rol van tech in de cultuursector'
    panel: true
  - name: Jasper Visser
    page: https://visschstam.com/
    function: Strategisch adviseur & Senior partner VISSCH+STAMM
    image: /img/sprekers/jaspervisser.jpg
    columns: 3
    subject: 'Rol van tech in de cultuursector'
    panel: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/foresightgent
  - title: facebook
    url: https://www.facebook.com/foresightgent/
  - title: instagram
    url: https://www.instagram.com/foresightgent/?hl=nl
  - title: github
    url: https://github.com/Lab9K

# Build settings
markdown: kramdown
permalink: pretty
