# Site settings
title: Museum of Things for People
email: foresight@digipolis.gent
url: https://lab9k.gent/
description: 'Onderzoek naar de waarde van Internet of Things in musea.'
baseurl: /
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# here you can add/remove navigation items. This works with local, and outbound links
navitems:
  - name: over
    url: '#about'
    class: page-scroll
  - name: Doel
    url: '#goal'
    class: page-scroll
  - name: Context
    url: '#context'
    class: page-scroll
  - name: Partners
    url: '#partners'
    class: page-scroll
  - name: blog
    url: 'https://medium.com/@MOTFP'
  - name: contact
    url: '#contact'
    class: page-scroll
  - name: events
    url: '/events'

# use the speaker.columns attribute to specify the width of a column. (out of 12 -> columns===4 means 3 columns per row)
speakers:
  # - name: John Doe
  #   page: https://www.example.com
  #   function: assistant space engineer
  #   image: https://source.unsplash.com/random/400x400/?portrait&sig=1
  #   columns: 4

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/foresightgent
  - title: facebook
    url: https://www.facebook.com/foresightgent/
  - title: instagram
    url: https://www.instagram.com/foresightgent/?hl=nl
  - title: github
    url: https://github.com/Lab9K

# Build settings
markdown: kramdown
permalink: pretty
