# Site settings
title: Museum of Things for People
email: pieterjan.pauwels@digipolis.gent
url: https://lab9k.gent/
description: 'Onderzoek naar de waarde van Internet of Things in musea.'
baseurl: /MOTFP
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# here you can add/remove navigation items. This works with local, and outbound links
# for links to the home page, you can include the id of the element you wish to scroll to.
# if you wish to enable slow scrolling to the element, you should add 'class: page-sroll' to the item.
# all links starting with '/' will be prepended with the baseurl of your website (triggering a page reload)
navitems:
  - name: over
    url: '#about'
    class: page-scroll
  - name: Doel
    url: '#goal'
    class: page-scroll
  - name: about
    url: '#about'
    class: page-scroll
  - name: blog
    # this is an example to trigger a page reload. notice how the class is still page-scroll,
    # triggering the reload will break scrolljacking
    url: 'https://medium.com/@foresightgent'
  - name: contact
    url: '#contact'
    class: page-scroll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Foresight
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: https://github.com/Lab9K

# Build settings
markdown: kramdown
permalink: pretty
